server:
  port: 8080


spring:
    application:
    name: spring-boot-redis
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        #druid相关配置
        druid:
          #监控统计拦截的filters
          filters: stat
          driver-class-name: com.mysql.cj.jdbc.Driver
          #基本属性
          url: jdbc:mysql://127.0.0.1:3306/distribute?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
          username: root
          password: jdsw123456
          #配置初始化大小/最小/最大
          initial-size: 1
          min-idle: 1
          max-active: 20
          #获取连接等待超时时间
          max-wait: 60000
          #间隔多久进行一次检测，检测需要关闭的空闲连接
          time-between-eviction-runs-millis: 60000
          #一个连接在池中最小生存的时间
          min-evictable-idle-time-millis: 300000
          validation-query: SELECT 'x'
          test-while-idle: true
          test-on-borrow: false
          test-on-return: false
          #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
          pool-prepared-statements: false
          max-pool-prepared-statement-per-connection-size: 20
    redis:
      password:
      timeout: 5000
    activiti:
     database-schema-update: true
      #false：false为默认值，设置为该值后，Activiti在启动时，会对比数据库表中保存的版本，如果没有表或者版本不匹配时，将在启动时抛出异常。
      #true：设置为该值后，Activiti会对数据库中所有的表进行更新，如果表不存在，则Activiti会自动创建。
      #create-drop：Activiti启动时，会执行数据库表的创建操作，在Activiti关闭时，执行数据库表的删除操作。
      #drop-create：Activiti启动时，执行数据库表的删除操作在Activiti关闭时，会执行数据库表的创建操作。
      #history-level: full
      #none：不保存任何的历史数据，因此，在流程执行过程中，这是最高效的。
        #activity：级别高于none，保存流程实例与流程行为，其他数据不保存。
        #audit：除activity级别会保存的数据外，还会保存全部的流程任务及其属性。audit为history的默认值。
        #full：保存历史数据的最高级别，除了会保存audit级别的数据外，还会保存其他全部流程相关的细节数据，包括一些流程参数等。

     history-level: full
     #保存历史数据级别设置为full最高级别，便于历史数据的追溯

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.mys.mbackstage.model


#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    returnPageInfo: check

filter:
  config:
    excludeUrls: /login,/menu/menuList,/distribute/excelNetwork,/telemark/excelNetwork,/distribute/uploadImg,/telemark/uploadImg,/distribute/uploadFile,/telemark/uploadFile,/K,/L,/Z #登录和注册不需过滤，直接放行
